// THIS FILE HAS BEEN GENERATED BY gen_decode_switch

use super::*;
use crate::registers::IndexRegister::X;
use crate::registers::IndexRegister::Y;

pub fn decode(opcode: u8) -> DecodedOpcode {
    match opcode {
        0x00 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Break,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0x01 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::ZeroPageIdxIndirect,
            operation: instr::InstructionOp::Or,
            index: Some(X),
        },
        0x02 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0x03 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0x04 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0x05 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::ZeroPage,
            operation: instr::InstructionOp::Or,
            index: None,
        },
        0x06 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::ZeroPageReadModifyWrite,
            operation: instr::InstructionOp::ShiftLeftMemory,
            index: None,
        },
        0x07 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0x08 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Push,
            operation: instr::InstructionOp::PushStatus,
            index: None,
        },
        0x09 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Immediate,
            operation: instr::InstructionOp::Or,
            index: None,
        },
        0x0A => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::ShiftLeftA,
            index: None,
        },
        0x0B => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0x0C => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0x0D => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Absolute,
            operation: instr::InstructionOp::Or,
            index: None,
        },
        0x0E => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::AbsoluteReadModifyWrite,
            operation: instr::InstructionOp::ShiftLeftMemory,
            index: None,
        },
        0x0F => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0x10 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Relative,
            operation: instr::InstructionOp::BranchPlus,
            index: None,
        },
        0x11 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::ZeroPageIndirectIdxRead,
            operation: instr::InstructionOp::Or,
            index: Some(Y),
        },
        0x12 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0x13 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0x14 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0x15 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::ZeroPageIdx,
            operation: instr::InstructionOp::Or,
            index: Some(X),
        },
        0x16 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::ZeroPageIdxReadModifyWrite,
            operation: instr::InstructionOp::ShiftLeftMemory,
            index: Some(X),
        },
        0x17 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0x18 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::ClearCarry,
            index: None,
        },
        0x19 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::AbsoluteIdxRead,
            operation: instr::InstructionOp::Or,
            index: Some(Y),
        },
        0x1A => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0x1B => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0x1C => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0x1D => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::AbsoluteIdxRead,
            operation: instr::InstructionOp::Or,
            index: Some(X),
        },
        0x1E => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::AbsoluteIdxReadModifyWrite,
            operation: instr::InstructionOp::ShiftLeftMemory,
            index: Some(X),
        },
        0x1F => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0x20 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::JumpSubroutine,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0x21 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::ZeroPageIdxIndirect,
            operation: instr::InstructionOp::And,
            index: Some(X),
        },
        0x22 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0x23 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0x24 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::ZeroPage,
            operation: instr::InstructionOp::Bit,
            index: None,
        },
        0x25 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::ZeroPage,
            operation: instr::InstructionOp::And,
            index: None,
        },
        0x26 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::ZeroPageReadModifyWrite,
            operation: instr::InstructionOp::RotateLeftMemory,
            index: None,
        },
        0x27 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0x28 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Pull,
            operation: instr::InstructionOp::PullStatus,
            index: None,
        },
        0x29 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Immediate,
            operation: instr::InstructionOp::And,
            index: None,
        },
        0x2A => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::RotateLeftA,
            index: None,
        },
        0x2B => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0x2C => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Absolute,
            operation: instr::InstructionOp::Bit,
            index: None,
        },
        0x2D => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Absolute,
            operation: instr::InstructionOp::And,
            index: None,
        },
        0x2E => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::AbsoluteReadModifyWrite,
            operation: instr::InstructionOp::RotateLeftMemory,
            index: None,
        },
        0x2F => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0x30 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Relative,
            operation: instr::InstructionOp::BranchMinus,
            index: None,
        },
        0x31 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::ZeroPageIndirectIdxRead,
            operation: instr::InstructionOp::And,
            index: Some(Y),
        },
        0x32 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0x33 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0x34 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0x35 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::ZeroPageIdx,
            operation: instr::InstructionOp::And,
            index: Some(X),
        },
        0x36 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::ZeroPageIdxReadModifyWrite,
            operation: instr::InstructionOp::RotateLeftMemory,
            index: Some(X),
        },
        0x37 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0x38 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::SetCarry,
            index: None,
        },
        0x39 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::AbsoluteIdxRead,
            operation: instr::InstructionOp::And,
            index: Some(Y),
        },
        0x3A => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0x3B => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0x3C => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0x3D => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::AbsoluteIdxRead,
            operation: instr::InstructionOp::And,
            index: Some(X),
        },
        0x3E => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::AbsoluteIdxReadModifyWrite,
            operation: instr::InstructionOp::RotateLeftMemory,
            index: Some(X),
        },
        0x3F => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0x40 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::ReturnInterrupt,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0x41 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::ZeroPageIdxIndirect,
            operation: instr::InstructionOp::Xor,
            index: Some(X),
        },
        0x42 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0x43 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0x44 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0x45 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::ZeroPage,
            operation: instr::InstructionOp::Xor,
            index: None,
        },
        0x46 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::ZeroPageReadModifyWrite,
            operation: instr::InstructionOp::ShiftRightMemory,
            index: None,
        },
        0x47 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0x48 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Push,
            operation: instr::InstructionOp::PushA,
            index: None,
        },
        0x49 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Immediate,
            operation: instr::InstructionOp::Xor,
            index: None,
        },
        0x4A => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::ShiftRightA,
            index: None,
        },
        0x4B => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0x4C => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::AbsoluteJump,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0x4D => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Absolute,
            operation: instr::InstructionOp::Xor,
            index: None,
        },
        0x4E => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::AbsoluteReadModifyWrite,
            operation: instr::InstructionOp::ShiftRightMemory,
            index: None,
        },
        0x4F => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0x50 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Relative,
            operation: instr::InstructionOp::BranchOverflowClear,
            index: None,
        },
        0x51 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::ZeroPageIndirectIdxRead,
            operation: instr::InstructionOp::Xor,
            index: Some(Y),
        },
        0x52 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0x53 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0x54 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0x55 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::ZeroPageIdx,
            operation: instr::InstructionOp::Xor,
            index: Some(X),
        },
        0x56 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::ZeroPageIdxReadModifyWrite,
            operation: instr::InstructionOp::ShiftRightMemory,
            index: Some(X),
        },
        0x57 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0x58 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::ClearInterruptDisable,
            index: None,
        },
        0x59 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::AbsoluteIdxRead,
            operation: instr::InstructionOp::Xor,
            index: Some(Y),
        },
        0x5A => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0x5B => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0x5C => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0x5D => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::AbsoluteIdxRead,
            operation: instr::InstructionOp::Xor,
            index: Some(X),
        },
        0x5E => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::AbsoluteIdxReadModifyWrite,
            operation: instr::InstructionOp::ShiftRightMemory,
            index: Some(X),
        },
        0x5F => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0x60 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::ReturnSubroutine,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0x61 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::ZeroPageIdxIndirect,
            operation: instr::InstructionOp::Add,
            index: Some(X),
        },
        0x62 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0x63 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0x64 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0x65 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::ZeroPage,
            operation: instr::InstructionOp::Add,
            index: None,
        },
        0x66 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::ZeroPageReadModifyWrite,
            operation: instr::InstructionOp::RotateRightMemory,
            index: None,
        },
        0x67 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0x68 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Pull,
            operation: instr::InstructionOp::PullA,
            index: None,
        },
        0x69 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Immediate,
            operation: instr::InstructionOp::Add,
            index: None,
        },
        0x6A => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::RotateRightA,
            index: None,
        },
        0x6B => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0x6C => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::AbsoluteIndirectJump,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0x6D => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Absolute,
            operation: instr::InstructionOp::Add,
            index: None,
        },
        0x6E => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::AbsoluteReadModifyWrite,
            operation: instr::InstructionOp::RotateRightMemory,
            index: None,
        },
        0x6F => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0x70 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Relative,
            operation: instr::InstructionOp::BranchOverflowSet,
            index: None,
        },
        0x71 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::ZeroPageIndirectIdxRead,
            operation: instr::InstructionOp::Add,
            index: Some(Y),
        },
        0x72 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0x73 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0x74 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0x75 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::ZeroPageIdx,
            operation: instr::InstructionOp::Add,
            index: Some(X),
        },
        0x76 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::ZeroPageIdxReadModifyWrite,
            operation: instr::InstructionOp::RotateRightMemory,
            index: Some(X),
        },
        0x77 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0x78 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::SetInterruptDisable,
            index: None,
        },
        0x79 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::AbsoluteIdxRead,
            operation: instr::InstructionOp::Add,
            index: Some(Y),
        },
        0x7A => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0x7B => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0x7C => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0x7D => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::AbsoluteIdxRead,
            operation: instr::InstructionOp::Add,
            index: Some(X),
        },
        0x7E => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::AbsoluteIdxReadModifyWrite,
            operation: instr::InstructionOp::RotateRightMemory,
            index: Some(X),
        },
        0x7F => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0x80 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0x81 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::ZeroPageIdxIndirect,
            operation: instr::InstructionOp::StoreA,
            index: Some(X),
        },
        0x82 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0x83 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0x84 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::ZeroPage,
            operation: instr::InstructionOp::StoreY,
            index: None,
        },
        0x85 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::ZeroPage,
            operation: instr::InstructionOp::StoreA,
            index: None,
        },
        0x86 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::ZeroPage,
            operation: instr::InstructionOp::StoreX,
            index: None,
        },
        0x87 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0x88 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::DecrementY,
            index: None,
        },
        0x89 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0x8A => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::TransferXToAccumulator,
            index: None,
        },
        0x8B => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0x8C => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Absolute,
            operation: instr::InstructionOp::StoreY,
            index: None,
        },
        0x8D => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Absolute,
            operation: instr::InstructionOp::StoreA,
            index: None,
        },
        0x8E => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Absolute,
            operation: instr::InstructionOp::StoreX,
            index: None,
        },
        0x8F => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0x90 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Relative,
            operation: instr::InstructionOp::BranchCarryClear,
            index: None,
        },
        0x91 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::ZeroPageIndirectIdxWrite,
            operation: instr::InstructionOp::StoreA,
            index: Some(Y),
        },
        0x92 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0x93 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0x94 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::ZeroPageIdx,
            operation: instr::InstructionOp::StoreY,
            index: Some(X),
        },
        0x95 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::ZeroPageIdx,
            operation: instr::InstructionOp::StoreA,
            index: Some(X),
        },
        0x96 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::ZeroPageIdx,
            operation: instr::InstructionOp::StoreX,
            index: Some(Y),
        },
        0x97 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0x98 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::TransferYToAccumulator,
            index: None,
        },
        0x99 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::AbsoluteIdxWrite,
            operation: instr::InstructionOp::StoreA,
            index: Some(Y),
        },
        0x9A => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::TransferXToStackPtr,
            index: None,
        },
        0x9B => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0x9C => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0x9D => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::AbsoluteIdxWrite,
            operation: instr::InstructionOp::StoreA,
            index: Some(X),
        },
        0x9E => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0x9F => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0xA0 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Immediate,
            operation: instr::InstructionOp::LoadY,
            index: None,
        },
        0xA1 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::ZeroPageIdxIndirect,
            operation: instr::InstructionOp::LoadA,
            index: Some(X),
        },
        0xA2 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Immediate,
            operation: instr::InstructionOp::LoadX,
            index: None,
        },
        0xA3 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0xA4 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::ZeroPage,
            operation: instr::InstructionOp::LoadY,
            index: None,
        },
        0xA5 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::ZeroPage,
            operation: instr::InstructionOp::LoadA,
            index: None,
        },
        0xA6 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::ZeroPage,
            operation: instr::InstructionOp::LoadX,
            index: None,
        },
        0xA7 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0xA8 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::TransferAccumulatorToY,
            index: None,
        },
        0xA9 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Immediate,
            operation: instr::InstructionOp::LoadA,
            index: None,
        },
        0xAA => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::TransferAccumulatorToX,
            index: None,
        },
        0xAB => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0xAC => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Absolute,
            operation: instr::InstructionOp::LoadY,
            index: None,
        },
        0xAD => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Absolute,
            operation: instr::InstructionOp::LoadA,
            index: None,
        },
        0xAE => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Absolute,
            operation: instr::InstructionOp::LoadX,
            index: None,
        },
        0xAF => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0xB0 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Relative,
            operation: instr::InstructionOp::BranchCarrySet,
            index: None,
        },
        0xB1 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::ZeroPageIndirectIdxRead,
            operation: instr::InstructionOp::LoadA,
            index: Some(Y),
        },
        0xB2 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0xB3 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0xB4 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::ZeroPageIdx,
            operation: instr::InstructionOp::LoadY,
            index: Some(X),
        },
        0xB5 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::ZeroPageIdx,
            operation: instr::InstructionOp::LoadA,
            index: Some(X),
        },
        0xB6 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::ZeroPageIdx,
            operation: instr::InstructionOp::LoadX,
            index: Some(Y),
        },
        0xB7 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0xB8 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::ClearOverflow,
            index: None,
        },
        0xB9 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::AbsoluteIdxRead,
            operation: instr::InstructionOp::LoadA,
            index: Some(Y),
        },
        0xBA => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::TransferStackPtrToX,
            index: None,
        },
        0xBB => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0xBC => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::AbsoluteIdxRead,
            operation: instr::InstructionOp::LoadY,
            index: Some(X),
        },
        0xBD => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::AbsoluteIdxRead,
            operation: instr::InstructionOp::LoadA,
            index: Some(X),
        },
        0xBE => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::AbsoluteIdxRead,
            operation: instr::InstructionOp::LoadX,
            index: Some(Y),
        },
        0xBF => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0xC0 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Immediate,
            operation: instr::InstructionOp::Cpy,
            index: None,
        },
        0xC1 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::ZeroPageIdxIndirect,
            operation: instr::InstructionOp::Cmp,
            index: Some(X),
        },
        0xC2 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0xC3 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0xC4 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::ZeroPage,
            operation: instr::InstructionOp::Cpy,
            index: None,
        },
        0xC5 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::ZeroPage,
            operation: instr::InstructionOp::Cmp,
            index: None,
        },
        0xC6 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::ZeroPageReadModifyWrite,
            operation: instr::InstructionOp::DecrementMemory,
            index: None,
        },
        0xC7 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0xC8 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::IncrementY,
            index: None,
        },
        0xC9 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Immediate,
            operation: instr::InstructionOp::Cmp,
            index: None,
        },
        0xCA => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::DecrementX,
            index: None,
        },
        0xCB => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0xCC => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Absolute,
            operation: instr::InstructionOp::Cpy,
            index: None,
        },
        0xCD => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Absolute,
            operation: instr::InstructionOp::Cmp,
            index: None,
        },
        0xCE => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::AbsoluteReadModifyWrite,
            operation: instr::InstructionOp::DecrementMemory,
            index: None,
        },
        0xCF => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0xD0 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Relative,
            operation: instr::InstructionOp::BranchNotEqual,
            index: None,
        },
        0xD1 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::ZeroPageIndirectIdxRead,
            operation: instr::InstructionOp::Cmp,
            index: Some(Y),
        },
        0xD2 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0xD3 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0xD4 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0xD5 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::ZeroPageIdx,
            operation: instr::InstructionOp::Cmp,
            index: Some(X),
        },
        0xD6 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::ZeroPageIdxReadModifyWrite,
            operation: instr::InstructionOp::DecrementMemory,
            index: Some(X),
        },
        0xD7 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0xD8 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::ClearDecimal,
            index: None,
        },
        0xD9 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::AbsoluteIdxRead,
            operation: instr::InstructionOp::Cmp,
            index: Some(Y),
        },
        0xDA => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0xDB => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0xDC => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0xDD => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::AbsoluteIdxRead,
            operation: instr::InstructionOp::Cmp,
            index: Some(X),
        },
        0xDE => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::AbsoluteIdxReadModifyWrite,
            operation: instr::InstructionOp::DecrementMemory,
            index: Some(X),
        },
        0xDF => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0xE0 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Immediate,
            operation: instr::InstructionOp::Cpx,
            index: None,
        },
        0xE1 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::ZeroPageIdxIndirect,
            operation: instr::InstructionOp::Sub,
            index: Some(X),
        },
        0xE2 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0xE3 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0xE4 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::ZeroPage,
            operation: instr::InstructionOp::Cpx,
            index: None,
        },
        0xE5 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::ZeroPage,
            operation: instr::InstructionOp::Sub,
            index: None,
        },
        0xE6 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::ZeroPageReadModifyWrite,
            operation: instr::InstructionOp::IncrementMemory,
            index: None,
        },
        0xE7 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0xE8 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::IncrementX,
            index: None,
        },
        0xE9 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Immediate,
            operation: instr::InstructionOp::Sub,
            index: None,
        },
        0xEA => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0xEB => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0xEC => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Absolute,
            operation: instr::InstructionOp::Cpx,
            index: None,
        },
        0xED => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Absolute,
            operation: instr::InstructionOp::Sub,
            index: None,
        },
        0xEE => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::AbsoluteReadModifyWrite,
            operation: instr::InstructionOp::IncrementMemory,
            index: None,
        },
        0xEF => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0xF0 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Relative,
            operation: instr::InstructionOp::BranchEqual,
            index: None,
        },
        0xF1 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::ZeroPageIndirectIdxRead,
            operation: instr::InstructionOp::Sub,
            index: Some(Y),
        },
        0xF2 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0xF3 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0xF4 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0xF5 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::ZeroPageIdx,
            operation: instr::InstructionOp::Sub,
            index: Some(X),
        },
        0xF6 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::ZeroPageIdxReadModifyWrite,
            operation: instr::InstructionOp::IncrementMemory,
            index: Some(X),
        },
        0xF7 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0xF8 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::SetDecimal,
            index: None,
        },
        0xF9 => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::AbsoluteIdxRead,
            operation: instr::InstructionOp::Sub,
            index: Some(Y),
        },
        0xFA => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0xFB => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0xFC => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
        0xFD => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::AbsoluteIdxRead,
            operation: instr::InstructionOp::Sub,
            index: Some(X),
        },
        0xFE => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::AbsoluteIdxReadModifyWrite,
            operation: instr::InstructionOp::IncrementMemory,
            index: Some(X),
        },
        0xFF => DecodedOpcode {
            sequence: instr::InstructionSequenceMode::Implied,
            operation: instr::InstructionOp::Nop,
            index: None,
        },
    }
}
